name: UI Tests CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ui

      # - name: Run server tests
      #   run: npm test
      #   working-directory: ui

      - name: Install cypress
        run: npm install cypress

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ui
          start: npm start # Command to start your server, adjust as needed
          wait-on: 'http://localhost:3000' # Adjust the URL/port as per your server
          wait-on-timeout: 60 # Time in seconds to wait for the server to start
          spec: cypress/e2e/E2ETest.cy.js # The path to the spec file

